package Command;

import Models.ClientGameList;
import Services.LoginService;

// This command allows a user to log in with a specific username and password
public class TheLoginCommand implements Command {
    private String username; // The username of the user logging in
    private String password; // The password of the user logging in
    // This field can hold multiple values:
        // When filled by the client: The address of the server to connect to
        // When filled by the server: The address of the client that sent the command
    private String ipAddress;
    private ClientGameList gameList; // A list of pending games to display
    // A token to be generated by the client to identify itself to the server, after login /
    // registration, this is replaced by the ipAddress
    private String authToken;

    @Override // Tells the login service to log the player in
    public void execute() {
        LoginService newService = new LoginService(); // Creates the new service
        // Tells the service to try to log the user in
        newService.doService(username, password, ipAddress, gameList, authToken);
    }

    // Creates a new request to log in with a username, password, server IP address,
    // and an authentication token
    public TheLoginCommand(String username, String password, String ipAddress, String authToken) {
        this.username = username;
        this.password = password;
        this.ipAddress = ipAddress;
        // The client doesn't know the pending games before the server provides them
        this.gameList = null;
        this.authToken = authToken;
    }
}